import 'dotenv/config';

export const HOST_REDIS = process.env.HOST_REDIS;
export const PORT_REDIS = process.env.PORT_REDIS;
export const USERNAME_REDIS = process.env.USERNAME_REDIS;
export const PASSWORD_REDIS = process.env.PASSWORD_REDIS;
export const USER_URL = process.env.USER_URL;
export const PRODUCTS_URL = process.env.PRODUCTS_URL;
export const PORT = process.env.PORT;
export const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
export const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
export const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;
export const STRIPE_SECRET = process.env.STRIPE_SECRET;
export const INTERNAL_API_SUCESS = process.env.INTERNAL_API_SUCESS;
export const INTERNAL_API_CANCEL = process.env.INTERNAL_API_CANCEL;
export const API_DOLAR = process.env.API_DOLAR;
export const CANCEL_URL = process.env.CANCEL_URL;
export const SUCESS_URL = process.env.SUCESS_URL;
export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
export const CALLBACK_URL = process.env.CALLBACK_URL;
export const GOOGLE_REDIRECT_FRONT = process.env.GOOGLE_REDIRECT_FRONT;
export const LOGIN_URL = process.env.LOGIN_URL;
export const HEADERS_TOKEN = process.env.HEADERS_TOKEN;
export const SESSION_SECRET = process.env.SESSION_SECRET;
export const SECRET_KEY = process.env.SECRET_KEY;
export const DATABASE_URL = process.env.DATABASE_URL;
