export const MS_PRODUCTS = 'PRODUCTS_SERVICE';
export const MS_USERS = 'USERS_SERVICE';
export const MS_AUTH = 'AUTH_SERVICE';
export const MS_PAYMENT = 'PAYMENT_SERVICE';
export const MS_APPOINTMENT = 'APPOINTMENT_SERVICE';
